// This file is generated by `npm run openapi`.
// Run the backend (e.g., uvicorn on http://localhost:8123) then:
//   npm run openapi
// The generated types will overwrite this placeholder.

// The openapi-typescript output exports `paths` (and often `components`).
// These placeholders keep the codebase compiling until you generate real types.
export interface paths {}
export interface components {}
