// This file is generated by `npm run openapi`.
// Run the backend (e.g., uvicorn on http://localhost:8123) then:
//   npm run openapi
// The generated types will overwrite this placeholder.

// The openapi-typescript output exports `paths` (and often `components`).
// These placeholders keep the codebase compiling until you generate real types.
export interface paths {
  "/health": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": { status: string };
          };
        };
      };
    };
  };
  "/health/ready": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": { status: string; environment: string; database: string };
          };
        };
      };
    };
  };
  "/health/echo": {
    post: {
      requestBody: {
        content: {
          "application/json": { message: string };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": { message: string };
          };
        };
      };
    };
  };
}
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface components {}
